name: 🛞 continuous-integration

on:
  pull_request:
    branches: [main]

jobs:
  validate-commits:
    name: validate commits
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Validate Conventional Commits
        uses: cangulo-actions/conventional-commits-validator@main
        id: validate-commits

  get-changes:
    name: 🔎 Get Changes
    uses: ./.github/workflows/shared-get-changes.yml

  lint-code:
    name: 🕺 Lint Code
    needs: get-changes
    if: needs.get-changes.outputs.js-modified == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: install packages
        run: npm install --only=dev

      - name: validate code style (eslint)
        run: npm run lint

      - name: explain how to fix code style
        if: failure()
        env:
          ESLINT_TUTORIAL: https://mojitocoder.medium.com/how-to-add-code-linting-for-a-node-js-project-b210d8759cd5
        run: |
          echo "# CI failed validating code style"    >> $GITHUB_STEP_SUMMARY
          echo "To fix the code style, run:"          >> $GITHUB_STEP_SUMMARY
          echo "npm run lint-fix"                     >> $GITHUB_STEP_SUMMARY
          echo "[ESLINT Tutorail]($ESLINT_TUTORIAL)"  >> $GITHUB_STEP_SUMMARY

  test-JS:
    name: 🧪 JS Tests
    needs: get-changes
    if: needs.get-changes.outputs.js-modified == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: install packages
        run: npm install

      - name: run JS tests (UT and index.js)
        run: npm run test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JS Tests  # Name of the check run which will be created
          path: reports/jest-*.xml
          reporter: jest-junit

  prepare-test-e2e:
    name: 🥡 zip cypress tests
    needs: get-changes
    if: needs.get-changes.outputs.action-modified == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cc repository
        uses: actions/checkout@v4.1.1

      - name: create cypress artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: cypress
          path: cypress

  test-e2e:
    name: 📽️ Execute Cypress in CrazyActionsTests repo
    needs:
      - prepare-test-e2e
      - get-changes
    if: needs.get-changes.outputs.action-modified == 'true'
    concurrency:  # concurrency set to avoid conflicts pushing to CrazyActionsTests repo
      group: e2e-tests
      cancel-in-progress: false
    runs-on: ubuntu-latest
    env:
      CYPRESS_GH_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}
      CYPRESS_GH_API_URL: https://api.github.com/repos/cangulo-actions/CrazyActionsTests
      CYPRESS_WAIT_TIME_CI_WORKFLOW: 25000  # wait 25 seconds before checking the CD workflow
      CYPRESS_API_RETRY_INTERVAL_MS: 10000  # retry every 10 seconds
      CYPRESS_API_RETRY_TIMEOUT_MS: 40000   # timeout after 40 seconds of retry
      CYPRESS_CC_BRANCH: ${{ github.head_ref }}
      CYPRESS_CC_PR_NUMBER: ${{ github.event.number }}
      CYPRESS_BRANCH_TO_CREATE: test-cc-pr-${{ github.event.number }}
      CYPRESS_GH_WORKFLOW_PREPARE_REPO_TIMEOUT: 30000 # wait 30 seconds before checking the reset repo workflow
    steps:
      - name: Checkout cangulo-actions/CrazyActionsTests repository
        uses: actions/checkout@v4.1.1
        with:
          repository: cangulo-actions/CrazyActionsTests
          ref: main
          token: ${{ secrets.GH_AUTOMATION_TOKEN }}

      - name: configure git credentials
        run: |
          git config user.name  "cangulo-cc-e2e-test[bot]"
          git config user.email "cangulo-cc-e2e-test[bot]@users.noreply.github.com"

      - name: 🥡 Download cypress artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: cypress
          path: cypress-cc

      - name: move cypress folder to root
        run: |
          rm -rf cypress                        # remove any local cypress folder
          mv cypress-cc/* . --force --verbose   # move cypress from artifact to root

      - name: 🚬 smoke tests
        uses: cypress-io/github-action@v6.6.0
        env:
          CYPRESS_BEFORE_ALL_PREPARE_REPO_ENABLED: "true" # execute reset-repo before and after tests
          CYPRESS_BEFORE_ALL_CLOSE_ANY_PR: "true"
        with:
          spec: cypress/e2e/smoke-test.feature

      - name: 🎪 e2e tests happy path
        uses: cypress-io/github-action@v6.6.0
        with:
          spec: cypress/e2e/pr-with-valid-commits.feature

      - name: 🎪 e2e tests invalid commits
        uses: cypress-io/github-action@v6.6.0
        env:
          CYPRESS_AFTER_ALL_PREPARE_REPO_ENABLED: "true"  # execute reset-repo after tests
          CYPRESS_AFTER_ALL_CLOSE_ANY_PR: "true"
        with:
          spec: cypress/e2e/pr-with-invalid-commits.feature
