name: 🛞 continuous-integration

on:
  pull_request:
    branches: [main]

env:
  GH_E2E_user: cangulo-cc-e2e-test[bot]
  GH_E2E_email: cangulo-cc-e2e-test[bot]@users.noreply.github.com

jobs:
  validate-commits:
    name: validate commits
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Validate Conventional Commits using the current branch
        uses: ./
        id: validate-commits

  get-changes:
    name: 🔎 Get Changes
    uses: ./.github/workflows/shared-get-changes.yml

  lint-code:
    name: 🕺 Lint Code
    needs: get-changes
    if: needs.get-changes.outputs.js-modified == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: install packages
        run: npm install --only=dev

      - name: validate code style (eslint)
        run: npm run lint

      - name: explain how to fix code style
        if: failure()
        env:
          ESLINT_TUTORIAL: https://mojitocoder.medium.com/how-to-add-code-linting-for-a-node-js-project-b210d8759cd5
        run: |
          echo "# CI failed validating code style"    >> $GITHUB_STEP_SUMMARY
          echo "To fix the code style, run:"          >> $GITHUB_STEP_SUMMARY
          echo "npm run lint-fix"                     >> $GITHUB_STEP_SUMMARY
          echo "[ESLINT Tutorial]($ESLINT_TUTORIAL)"  >> $GITHUB_STEP_SUMMARY

  test-JS:
    name: 🧪 JS Tests
    needs: get-changes
    if: needs.get-changes.outputs.js-modified == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: install packages
        run: npm install

      - name: run JS tests (UT and index.js)
        run: npm run test

      - name: Test Report
        uses: dorny/test-reporter@86a20101473378575dcbaa709a4f2b772001fbbb
        if: success() || failure()
        with:
          name: JS Tests # Name of the check run which will be created
          path: reports/jest-*.xml
          reporter: jest-junit

  test-e2e:
    name: ${{ matrix.scenario }}
    needs: get-changes
    if: needs.get-changes.outputs.action-modified == 'true' || needs.get-changes.outputs.e2e-tests-modified == 'true'
    concurrency:  # concurrency set to avoid conflicts pushing to each repo
      group: e2e-tests-${{ matrix.spec }}
      cancel-in-progress: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - scenario: 🚬 smoke tests
            spec: cypress/e2e/smoke-test.feature
            key: smoke-test

          - scenario: Invalid Commit Type
            spec: cypress/e2e/invalid-commits-type.feature
            key: invalid-commits-type

          - scenario: Invalid Commit Msg
            spec: cypress/e2e/invalid-commits-msg.feature
            key: invalid-commits-msg

          - scenario: Invalid scope
            spec: cypress/e2e/invalid-commits-scope.feature
            key: invalid-commits-scope

          - scenario: Invalid configuration
            spec: cypress/e2e/invalid-configuration.feature
            key: invalid-configuration

          - scenario: "Feat: conf.commits"
            spec: cypress/e2e/feat-conf-commits-types.feature
            key: feat-conf-commits-types

          - scenario: "Feat: conf.scopes"
            spec: cypress/e2e/feat-conf-commits-scopes.feature
            key: feat-conf-commits-scopes

          - scenario: Feat - Calculate next release when breaking changes are introduced
            spec: cypress/e2e/feat-calculate-next-release-break.feature
            key: feat-calc-next-release-break

          - scenario: Feat - Calculate next release when docs are updated
            spec: cypress/e2e/feat-calculate-next-release-docs.feature
            key: feat-calc-next-release-docs

          - scenario: Feat - Version Prefix
            spec: cypress/e2e/feat-calculate-version-prefix.feature
            key: feat-calculate-version-prefix

          - scenario: Feat - Label PR with the next release
            spec: cypress/e2e/feat-label-pr-with-release-type.feature
            key: feat-label-pr-with-release-type

          - scenario: Feat - Label PR with commit types
            spec: cypress/e2e/feat-label-pr-with-commit-types.feature
            key: feat-label-pr-with-commit-types

          - scenario: Feat - Label PR with commit scopes
            spec: cypress/e2e/feat-label-pr-with-scopes.feature
            key: feat-label-pr-with-scopes

    runs-on: ubuntu-latest
    env:
      GH_ORG: cangulo-actions-test
      GH_REPO_TO_RUN_E2E: cc-PR-${{ github.event.number }}-${{ matrix.key }}
    steps:
      - name: Checkout semver repository
        uses: actions/checkout@v4.1.1

      - name: 🧹 delete any temporary repository
        uses: ./.github/actions/delete-temp-repos
        with:
          org: ${{ env.GH_ORG }}
          repo: ${{ env.GH_REPO_TO_RUN_E2E }}
          gh-token: ${{ secrets.CANGULO_BOT_DELETE_REPO }}

      - name: 🧪 run cypress e2e tests
        uses: cypress-io/github-action@v6.6.0
        with:
          spec: ${{ matrix.spec }}
          working-directory: cypress
          publish-summary: false
        env:
          CYPRESS_TEST_KEY: ${{ matrix.key }}
          CYPRESS_GH_ORG: ${{ env.GH_ORG }}
          CYPRESS_GH_TOKEN: ${{ secrets.CANGULO_BOT_MODIFY_GH_WORKFLOWS }}
          CYPRESS_GH_API_URL: https://api.github.com
          CYPRESS_WAIT_TIME_CI_WORKFLOW: 25000  # wait 25 seconds before checking the CD workflow
          CYPRESS_API_RETRY_INTERVAL_MS: 10000  # retry every 10 seconds
          CYPRESS_API_RETRY_TIMEOUT_MS: 40000   # timeout after 40 seconds of retry
          CYPRESS_CC_BRANCH: ${{ github.head_ref }}
          CYPRESS_CC_PR_NUMBER: ${{ github.event.number }}
          CYPRESS_GH_USER_NAME: ${{ env.GH_E2E_user }}
          CYPRESS_GH_USER_EMAIL: ${{ env.GH_E2E_email }}

      - name: Print link to the repo
        uses: actions/github-script@v7.0.1
        if: failure()
        env:
          OWNER: ${{ env.GH_ORG }}
          REPO: ${{ env.GH_REPO_TO_RUN_E2E }}
          TEST_SCENARIO: ${{ matrix.scenario }}
          TEST_SPEC: ${{ matrix.spec }}
        with:
          script: |
            const owner     = process.env.OWNER
            const repo      = process.env.REPO
            const scenario  = process.env.TEST_SCENARIO
            const spec      = process.env.TEST_SPEC
            const linkRepo  = `https://github.com/${owner}/${repo}/actions`

            core
              .summary
              .addHeading(`🛑⚠️ Failed test for '${scenario}' (${spec})`)
              .addLink(`Link to ${owner}/${repo} repo`, linkRepo)
              .write()

      - name: 🧹 delete any temporary repository
        uses: ./.github/actions/delete-temp-repos
        with:
          org: ${{ env.GH_ORG }}
          repo: ${{ env.GH_REPO_TO_RUN_E2E }}
          gh-token: ${{ secrets.CANGULO_BOT_DELETE_REPO }}
